// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	maxbot "github.com/max-messenger/max-bot-api-client-go"
	mock "github.com/stretchr/testify/mock"
)

// MessageSender is an autogenerated mock type for the MessageSender type
type MessageSender struct {
	mock.Mock
}

type MessageSender_Expecter struct {
	mock *mock.Mock
}

func (_m *MessageSender) EXPECT() *MessageSender_Expecter {
	return &MessageSender_Expecter{mock: &_m.Mock}
}

// Send provides a mock function with given fields: _a0, _a1
func (_m *MessageSender) Send(_a0 context.Context, _a1 *maxbot.Message) (string, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *maxbot.Message) (string, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *maxbot.Message) string); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *maxbot.Message) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MessageSender_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MessageSender_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *maxbot.Message
func (_e *MessageSender_Expecter) Send(_a0 interface{}, _a1 interface{}) *MessageSender_Send_Call {
	return &MessageSender_Send_Call{Call: _e.mock.On("Send", _a0, _a1)}
}

func (_c *MessageSender_Send_Call) Run(run func(_a0 context.Context, _a1 *maxbot.Message)) *MessageSender_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*maxbot.Message))
	})
	return _c
}

func (_c *MessageSender_Send_Call) Return(_a0 string, _a1 error) *MessageSender_Send_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MessageSender_Send_Call) RunAndReturn(run func(context.Context, *maxbot.Message) (string, error)) *MessageSender_Send_Call {
	_c.Call.Return(run)
	return _c
}

// NewMessageSender creates a new instance of MessageSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMessageSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *MessageSender {
	mock := &MessageSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
