// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	schemes "github.com/max-messenger/max-bot-api-client-go/schemes"
	mock "github.com/stretchr/testify/mock"
)

// UpdatesProvider is an autogenerated mock type for the UpdatesProvider type
type UpdatesProvider struct {
	mock.Mock
}

type UpdatesProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *UpdatesProvider) EXPECT() *UpdatesProvider_Expecter {
	return &UpdatesProvider_Expecter{mock: &_m.Mock}
}

// GetUpdates provides a mock function with given fields: _a0
func (_m *UpdatesProvider) GetUpdates(_a0 context.Context) <-chan schemes.UpdateInterface {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetUpdates")
	}

	var r0 <-chan schemes.UpdateInterface
	if rf, ok := ret.Get(0).(func(context.Context) <-chan schemes.UpdateInterface); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan schemes.UpdateInterface)
		}
	}

	return r0
}

// UpdatesProvider_GetUpdates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUpdates'
type UpdatesProvider_GetUpdates_Call struct {
	*mock.Call
}

// GetUpdates is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *UpdatesProvider_Expecter) GetUpdates(_a0 interface{}) *UpdatesProvider_GetUpdates_Call {
	return &UpdatesProvider_GetUpdates_Call{Call: _e.mock.On("GetUpdates", _a0)}
}

func (_c *UpdatesProvider_GetUpdates_Call) Run(run func(_a0 context.Context)) *UpdatesProvider_GetUpdates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *UpdatesProvider_GetUpdates_Call) Return(_a0 <-chan schemes.UpdateInterface) *UpdatesProvider_GetUpdates_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UpdatesProvider_GetUpdates_Call) RunAndReturn(run func(context.Context) <-chan schemes.UpdateInterface) *UpdatesProvider_GetUpdates_Call {
	_c.Call.Return(run)
	return _c
}

// NewUpdatesProvider creates a new instance of UpdatesProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUpdatesProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *UpdatesProvider {
	mock := &UpdatesProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
